// selector.ts — builds a unique CSS selector for any DOM element.

/**
 * If el is inside a data-component element (or is one itself), returns the
 * component root. Otherwise returns el unchanged.
 */
export function snapToComponent(el: Element): Element {
  // If el itself is the component root, return it.
  if (el.getAttribute("data-component")) return el;
  // Walk up to find the nearest component root.
  let node: Element | null = el.parentElement;
  while (node && node !== document.documentElement) {
    if (node.getAttribute("data-component")) return node;
    node = node.parentElement;
  }
  return el;
}

/**
 * Returns the most specific stable CSS selector for el.
 * Uses data-component attributes as stable anchors where available,
 * falling back to data-testid, id, and nth-of-type paths.
 */
export function buildSelector(el: Element): string {
  const parts: string[] = [];
  let current: Element | null = el;

  while (current && current !== document.documentElement) {
    // data-testid — most stable anchor, stop here.
    const testId = current.getAttribute("data-testid");
    if (testId) {
      parts.unshift(`[data-testid="${CSS.escape(testId)}"]`);
      break;
    }

    // Stable id — stop here.
    if (current.id && !looksAutoGenerated(current.id)) {
      parts.unshift(`#${CSS.escape(current.id)}`);
      break;
    }

    // data-component — use as anchor, then continue walking up so we can
    // disambiguate siblings with the same component name.
    const comp = current.getAttribute("data-component");
    if (comp) {
      const parent = current.parentElement;
      if (parent) {
        const compSiblings = Array.from(parent.children).filter(
          (c) => c.getAttribute("data-component") === comp
        );
        if (compSiblings.length > 1) {
          const idx = compSiblings.indexOf(current) + 1;
          parts.unshift(`[data-component="${CSS.escape(comp)}"]:nth-of-type(${compSiblings.indexOf(current as Element) + 1})`);
          // Use actual nth-of-type among all same-tag siblings for CSS validity.
          const tagSiblings = Array.from(parent.children).filter(
            (c) => c.tagName === current!.tagName
          );
          const tagIdx = tagSiblings.indexOf(current) + 1;
          parts[0] = `[data-component="${CSS.escape(comp)}"]:nth-of-type(${tagIdx})`;
        } else {
          parts.unshift(`[data-component="${CSS.escape(comp)}"]`);
        }
        // Parent is itself a component — that's a sufficient anchor chain; stop.
        if (parent.getAttribute("data-component")) {
          const parentComp = parent.getAttribute("data-component")!;
          parts.unshift(`[data-component="${CSS.escape(parentComp)}"]`);
          break;
        }
        current = parent;
        continue;
      } else {
        parts.unshift(`[data-component="${CSS.escape(comp)}"]`);
        break;
      }
    }

    // Plain element — compute nth-of-type among same-tag siblings.
    const parent = current.parentElement;
    const tag = current.tagName.toLowerCase();
    if (parent) {
      const siblings = Array.from(parent.children).filter(
        (c) => c.tagName === current!.tagName
      );
      if (siblings.length > 1) {
        const idx = siblings.indexOf(current) + 1;
        parts.unshift(`${tag}:nth-of-type(${idx})`);
      } else {
        parts.unshift(tag);
      }
    } else {
      parts.unshift(tag);
    }

    current = parent;
  }

  return parts.join(" > ");
}

function looksAutoGenerated(id: string): boolean {
  return /^\d+$/.test(id) || /[:\[\]{}]/.test(id) || id.length > 50;
}

/**
 * Returns the nearest data-component value found on el or any ancestor,
 * or null if none exists.
 */
export function nearestComponent(el: Element): string | null {
  let node: Element | null = el;
  while (node && node !== document.documentElement) {
    const v = node.getAttribute("data-component");
    if (v) return v;
    node = node.parentElement;
  }
  return null;
}

/**
 * Returns a human-readable label for the element (for display in UI).
 * If the element is inside a component, returns "ComponentName > tag > tag"
 * showing the path from the component boundary down to the element.
 * Falls back to a tag/id/class description when no data-component is found.
 */
export function elementLabel(el: Element): string {
  let node: Element | null = el;
  const inner: string[] = [];

  while (node && node !== document.documentElement) {
    const component = node.getAttribute("data-component");
    if (component) {
      // inner is accumulated innermost-first; reverse for top-down order.
      return [component, ...inner.reverse()].join(" > ");
    }
    inner.push(node.tagName.toLowerCase());
    node = node.parentElement;
  }

  const tag = el.tagName.toLowerCase();
  const id = el.id ? `#${el.id}` : "";
  const cls = el.classList.length
    ? "." + Array.from(el.classList).slice(0, 2).join(".")
    : "";
  return `<${tag}${id}${cls}>`;
}
