// selector.ts — builds a unique CSS selector for any DOM element.

/**
 * Returns the most specific stable CSS selector for el.
 * Priority: data-testid > id > composed nth-child path.
 */
export function buildSelector(el: Element): string {
  // 1. data-testid
  const testId = el.getAttribute("data-testid");
  if (testId) return `[data-testid="${CSS.escape(testId)}"]`;

  // 2. id (only if it looks stable, not auto-generated)
  if (el.id && !looksAutoGenerated(el.id)) {
    return `#${CSS.escape(el.id)}`;
  }

  // 3. Walk up the tree building a unique path.
  return buildPath(el);
}

function looksAutoGenerated(id: string): boolean {
  // Heuristic: IDs that are purely numeric or contain colons/random suffixes.
  return /^\d+$/.test(id) || /[:\[\]{}]/.test(id) || id.length > 50;
}

function buildPath(el: Element): string {
  const parts: string[] = [];
  let current: Element | null = el;

  while (current && current !== document.documentElement) {
    const tag = current.tagName.toLowerCase();
    const parent = current.parentElement;

    // If the element has a stable id or data-testid, anchor there.
    const testId = current.getAttribute("data-testid");
    if (testId) {
      parts.unshift(`[data-testid="${CSS.escape(testId)}"]`);
      break;
    }
    if (current.id && !looksAutoGenerated(current.id)) {
      parts.unshift(`#${CSS.escape(current.id)}`);
      break;
    }

    // Compute nth-child index among same-tag siblings.
    if (parent) {
      const siblings = Array.from(parent.children).filter(
        (c) => c.tagName === current!.tagName
      );
      if (siblings.length > 1) {
        const idx = siblings.indexOf(current) + 1;
        parts.unshift(`${tag}:nth-of-type(${idx})`);
      } else {
        parts.unshift(tag);
      }
    } else {
      parts.unshift(tag);
    }

    current = parent;
  }

  return parts.join(" > ");
}

/**
 * Returns a human-readable label for the element (for display in UI).
 * If the element is inside a component, returns "ComponentName > tag > tag"
 * showing the path from the component boundary down to the element.
 * Falls back to a tag/id/class description when no data-component is found.
 */
export function elementLabel(el: Element): string {
  let node: Element | null = el;
  const inner: string[] = [];

  while (node && node !== document.documentElement) {
    const component = node.getAttribute("data-component");
    if (component) {
      const parts = [component, ...inner.reverse()];
      return parts.join(" > ");
    }
    inner.push(node.tagName.toLowerCase());
    node = node.parentElement;
  }

  const tag = el.tagName.toLowerCase();
  const id = el.id ? `#${el.id}` : "";
  const cls = el.classList.length
    ? "." + Array.from(el.classList).slice(0, 2).join(".")
    : "";
  return `<${tag}${id}${cls}>`;
}
